version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres_local
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped